# Generated by Django 4.1.13 on 2024-02-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0002_admin_level_admin_orderid_admin_parentcategoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Level',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='OrderID',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='ParentCategoryID',
        ),
    ]
