# Generated by Django 4.1.13 on 2024-04-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
