# Generated by Django 4.1.13 on 2024-02-15 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Level',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='OrderID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='ParentCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
