# Generated by Django 4.1.13 on 2024-02-19 13:04

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pbl', '0003_remove_admin_level_remove_admin_orderid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='message',
        ),
        migrations.AlterField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(related_name='admin_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(related_name='admin_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('message', models.TextField()),
                ('groups', models.ManyToManyField(related_name='contact_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='contact_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
